name: Jekyll Themes
url: http://small-kangaroo.cloudvent.net
description: Insert tagline here

permalink: /themes/:title/

pygments: true
paginate: 10

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']